# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SompaData.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "SensorReport" do
    optional :device_id, :uint32, 1
    optional :sensor_id, :uint32, 2
    optional :timestamp, :uint32, 3
    optional :wifi_failcount, :uint32, 8
    optional :wifi_id, :uint32, 9
    optional :boot_count, :uint32, 10
    optional :millis, :uint32, 11
    oneof :value do
      optional :f, :float, 4
      optional :percentage, :uint32, 5
      optional :val, :int32, 6
      optional :b, :bool, 7
    end
  end
  add_message "ServerResponse" do
    optional :goto_sleep_seconds, :uint32, 1
    optional :upgrade_available, :bool, 2
    optional :start_ota_ap, :bool, 3
    optional :firmware_url, :string, 4
    optional :spiffs_url, :string, 5
  end
  add_message "Ping" do
    optional :operation, :enum, 1, "Ping.Op"
    optional :number, :uint32, 2
  end
  add_enum "Ping.Op" do
    value :PING, 0
    value :PONG, 1
  end
end

SensorReport = Google::Protobuf::DescriptorPool.generated_pool.lookup("SensorReport").msgclass
ServerResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ServerResponse").msgclass
Ping = Google::Protobuf::DescriptorPool.generated_pool.lookup("Ping").msgclass
Ping::Op = Google::Protobuf::DescriptorPool.generated_pool.lookup("Ping.Op").enummodule
